### ISSUE TITLE
Please provide a How To

### ISSUE THREAD

**Issue by qoomon** [qzz0518/remove-HyperSwitch-expired-dialog#3]
Hi first of all thanks for your patch.

Anyway could you provide some details on how you managed to patch the executable?

**Comment by qzz0518** [comment]
The whole reverse process isn't too complicated.
It uses the keyword "expired," looks up the specific execution method, overwrites it with an empty method, and repackages the new executable file (because the software isn't encrypted, the repackaged file is available and doesn't crash).

By the way, the only working reverse software I found was the [Hopper Disassembler](https://www.hopperapp.com/)

**Comment by qoomon** [comment]
Thanks a lot.
